### ISSUE TITLE
这个垃圾项目就是在灌水，没人看，也别看了🤮

### ISSUE THREAD

**Issue by duanNT** [duanhf2012/origin#840]
### 呵呵🙃，就是在刷星星嘛，骗星星嘛，没意思！
 ![Trending](https://user-images.githubusercontent.com/65040197/81438635-aa3a5a80-919f-11ea-9a88-c9502569d677.png)

**Comment by HCWong01** [comment]
一点开就发现星星都刷，顿时就恶心了，没意思

**Comment by duanNT** [comment]
下辈子请好好做人 🖕

**Comment by HCWong01** [comment]
什么玩意啊 🤢

**Comment by RiseInRose** [comment]
为什么说是垃圾项目啊？理由是啥？
