### ISSUE TITLE
写的什么玩意，垃圾货，根本用不了!

### ISSUE THREAD

**Issue by HCWong01** [duanhf2012/origin#841]
# 呵呵🙃，都是刷星星的，没意思
 ![Trending](https://user-images.githubusercontent.com/65040197/81438635-aa3a5a80-919f-11ea-9a88-c9502569d677.png)

**Comment by duanNT** [comment]
败类 🖕

**Comment by HCWong01** [comment]
好无耻啊 🖕

**Comment by duanNT** [comment]
是啊，太恶心了 🖕

**Comment by duanNT** [comment]
下辈子请好好做人 🚮
