### ISSUE TITLE
cluster配置这里感觉有点抽象

### ISSUE THREAD

**Issue by NanTaiYue** [duanhf2012/origin#875]
1.cluster的配置支持热加载吗？比如我已部署了一个3个node的集群，现在需要增加一个节点，是必须重启所有节点吗？
2.既然每个节点下会去配置service的信息，比如tcpservice和wsservice的地址，端口等信息，还有必要配置公共service的必要吗？公共service配置主要的作用是什么？

**Comment by duanhf2012** [comment]
1. cluster配置不允许热加载，因为node信息一般是在计划部署时确定好的。如果你的架构设计合理，可以使用node滚动更新。origin引擎是支持动态服务发现（v2版本加入了etcd支持），当有node启动时，其他node或服务会获得新加入进来的服务。
2.服务支持公共配置与指定nodeid结点配合，在某些业务场景下，需要共用或者特例化配置。为了应用不同的场景才有这样的设计。
3.另外origin的配置不是按文件名来区分功能。还是按照json配置的key名来区分的，这意味着您可以根据自己的需要拆分到不同的配置中。

**Comment by NanTaiYue** [comment]
非常感谢您的答疑👍
